using Test

normalize_ws(s::AbstractString) = replace(s, r"\s+" => " ")

@testset "TN note large-N cooling qualifications" begin
    note_path = joinpath(@__DIR__, "..", "Notes", "NotesTN", "CoolingAlgTN.tex")
    map_path = joinpath(@__DIR__, "..", "Notes", "NotesED", "MapToSpin.tex")
    evidence_path = joinpath(@__DIR__, "..", "docs", "largeN_effective_bond_dimensions.md")
    plan_path = joinpath(@__DIR__, "..", "docs", "multi_frequency_cooling_plan.md")
    params_path = joinpath(@__DIR__, "..", "src", "parameter_types.jl")
    source_path = joinpath(@__DIR__, "..", "src", "mode_analysis.jl")
    driver_path = joinpath(@__DIR__, "..", "scripts", "validation",
                            "run_largeN_multifrequency_tn_scaling.jl")
    summary_path = joinpath(@__DIR__, "..", "scripts", "validation",
                            "summarize_largeN_bond_dimensions.jl")

    note_text = read(note_path, String)
    note_flat = normalize_ws(note_text)
    note_lower = lowercase(note_flat)
    map_flat = normalize_ws(read(map_path, String))
    evidence_flat = normalize_ws(read(evidence_path, String))
    plan_flat = normalize_ws(read(plan_path, String))
    plan_lower = lowercase(plan_flat)
    params_flat = normalize_ws(read(params_path, String))
    source_flat = normalize_ws(read(source_path, String))
    driver_flat = normalize_ws(read(driver_path, String))
    summary_flat = normalize_ws(read(summary_path, String))

    # These anchors intentionally couple the note to the source documents.
    # Update them together when the notation or bond-dimension evidence changes.
    @test occursin("We study a repeated bath-reset cooling map whose intended fixed point", note_flat)
    @test occursin("Whether a given implementation prepares the ground state is a dynamical and numerical question", note_flat)
    @test occursin("A favorable resonant transfer can then excite the ancillary system", note_flat)
    @test occursin("whether it actually produces a lower system energy depends on the coupling, detuning, cycle time, and numerical approximation", note_flat)
    @test occursin(raw"\Delta E_{\mathrm{fp}}", note_flat)
    @test occursin("Ground-state preservation is the special case", note_flat)
    @test occursin("not a formal consequence of appending a fresh bath ground state", note_flat)
    @test occursin("compare the trajectory with the available ground-state reference", note_flat)
    @test occursin("stable when the trajectory sampling, averaging window, and bond-dimension cap are varied", note_flat)
    @test occursin("This low-entanglement assumption is part of the numerical validation problem", note_flat)
    @test occursin("when the evolved system-bath MPS, the retained system MPS, or the TDVP sweep observer reaches the imposed bond cap", note_flat)
    @test occursin("not as a final demonstration of ground-state preparation", note_flat)
    @test occursin("Two cooling cycles are not physically meaningful", note_flat)
    @test occursin("driver now treats MCWF/MPS as the default production-sized tensor-network path", note_flat)
    @test occursin("the preferred initial-state selector is \\texttt{--init-state}; the stored HDF5 protocol field is \\texttt{init\\_state}", note_flat)
    @test occursin("The legacy spelling \\texttt{--init\\_state} is accepted as a command-line compatibility alias", note_flat)
    @test occursin("historically named \\texttt{init\\_type}; this is not the public protocol key", note_flat)
    @test occursin("For the public protocol value \\texttt{init\\_state=\"theta\"}", note_flat)
    @test occursin("entered as \\texttt{--init-state theta}", note_flat)
    @test occursin("they do not establish scalable cooling to the ground state", note_flat)
    @test occursin("historical bond-cap/truncation-pressure diagnostics", note_flat)
    @test occursin("do not store measured truncation-error histories", note_flat)
    @test occursin("finite-window noise-response diagnostics", note_flat)
    @test occursin("historical noisy MPO panels as finite-window diagnostics of the truncated channel response to the applied noise model", note_flat)
    @test occursin("a robustness claim requires the same bond-dimension, positivity, and trajectory-convergence checks", note_flat)
    @test occursin("archived pilot outputs use truncation caps up to \\(D\\leq 100\\)", note_flat)
    @test occursin("individual plotted panels below state their own fixed bond caps", note_flat)
    @test occursin("The displayed fixed-bond MPO panels use system sizes \\(N=50,100\\), bond dimension \\(D\\leq 20\\)", note_flat)
    @test occursin("archived pilot outputs use trajectory caps up to \\(D\\leq 40\\)", note_flat)
    @test occursin("individual plotted panels below state their own fixed trajectory bond caps", note_flat)
    @test occursin("Each trajectory starts from the same pure product state, and stochastic Pauli errors are sampled after each cooling step. The bond dimension is \$D \\leq 20\$", note_flat)
    @test occursin("D_{\\mathrm{sb}}^{\\mathrm{eff}}=394, 862, 518, 737", note_flat)
    @test occursin("the TDVP sweep observer reaches the cap during cycle 3 sweep 4", note_flat)
    @test occursin(raw"\texttt{not\_converged\_system\_and\_evolved\_and}", note_flat)
    @test occursin(raw"\texttt{\_tdvp\_sweep\_cap}", note_flat)
    @test occursin("R = 1: Dsys_eff = 309, Dsb_eff = 394", evidence_flat)
    @test occursin("R = 2: Dsys_eff = 637, Dsb_eff = 862", evidence_flat)
    @test occursin("R = 5: Dsys_eff = 399, Dsb_eff = 518", evidence_flat)
    @test occursin("R = 10: Dsys_eff = 489, Dsb_eff = 737", evidence_flat)
    @test occursin("Dtdvp_sweep_eff", evidence_flat)
    @test occursin("tdvp_sweep_max_bond", evidence_flat)
    @test occursin("tdvp_sweep_saturation_cycle", evidence_flat)
    @test occursin("detuning coverage", evidence_flat)
    @test occursin("full_grid_observed", evidence_flat)
    @test occursin("stopped_partial_grid", evidence_flat)
    @test occursin("single_detuning", evidence_flat)
    @test occursin("do not store measured per-bond truncation-error time series", evidence_flat)
    @test occursin("truncation_error_history_status = not_recorded", evidence_flat)
    @test occursin("legacy_missing", evidence_flat)
    @test occursin("measured", evidence_flat)
    @test occursin("empty", evidence_flat)
    @test occursin("not a measured discarded-weight history", evidence_flat)
    @test occursin("bond-cap and truncation-pressure diagnostics", evidence_flat)
    @test occursin("If any mode-observable dataset is present, the summary requires the complete", evidence_flat)
    @test occursin("A partial payload is rejected rather than summarized as `n/a`", evidence_flat)
    @test occursin("`completed/requested periods` column divides those cycle counts by `R`", evidence_flat)
    @test occursin("an `R = 10` row with five completed cycles is shown as only `0.50` completed schedule periods", evidence_flat)
    @test occursin("`visited detunings` column counts distinct stored detuning values", evidence_flat)
    @test occursin("the realized detuning coverage before the cap, not the intended full grid", evidence_flat)
    @test occursin("`traj cycles/hour` is computed as", evidence_flat)
    @test occursin("It is therefore a throughput diagnostic, not a cooling-performance metric", evidence_flat)
    @test occursin("single-run throughput from the stored HDF5 provenance", plan_flat)
    @test occursin("test and study whether these strategies carry over", plan_flat)
    @test occursin("computes the generic setup reference Δ = E₁ − E₀ if delta=nothing", plan_flat)
    @test occursin("builds the backend-appropriate system-bath representation for Δ", plan_flat)
    @test occursin("ED setup stores a sparse full system-bath matrix", plan_flat)
    @test occursin("TN continuous setup stores an MPO Hamiltonian", plan_flat)
    @test occursin("TN Trotter setup stores interleaved gates, with an MPO Hamiltonian present only on the support paths that need one", plan_flat)
    @test !occursin("builds H_SB(Δ) as MPO", plan_flat)
    @test occursin("This generic setup-gap convention remains the default for ordinary ED/TN single-detuning runs", plan_flat)
    @test occursin("the reference is the many-body generic pair scale `2 min_{sin(phi_k) != 0} epsilon_k`", plan_flat)
    @test occursin("on the deterministic parity-`+1` Fourier grid selected before any trajectory-specific state parity is measured", plan_flat)
    @test occursin("If later mode metadata records a different `mode_gF`, that metadata remains the source of truth for the stored observables", plan_flat)
    @test occursin("the detuning reference is setup-grid provenance, not a reconstruction from `mode_ek_values`", plan_flat)
    @test occursin("The stored `mode_ek_values` remain positive single-quasiparticle gaps used to label modes and resonance plots", plan_flat)
    @test occursin("they are not by themselves the automatic bath-detuning reference for the parity-preserving Ising cooling channel", plan_flat)
    @test occursin("on the deterministic `parity=+1` setup grid selected before any trajectory-specific state parity is measured", driver_flat)
    @test occursin("Later `mode_gF` metadata remains the source of truth for the measured mode-observable grid", driver_flat)
    @test !occursin("on the same Fourier grid as the mode observables", driver_flat)
    @test occursin("on the deterministic `parity=+1` setup grid selected before any trajectory-specific state parity is measured", evidence_flat)
    @test occursin("The measured `mode_gF` and `mode_gF_source` metadata remain the source of truth for the stored `mode_hk` rows", evidence_flat)
    @test !occursin("on the same parity-aware Fourier grid as `mode_hk`", evidence_flat)
    @test occursin(raw"\texttt{ising\_mode\_detuning\_preserves\_px}", map_flat)
    @test occursin("The Fourier/Bogoliubov diagnostics below are closed-chain transverse-field Ising diagnostics", map_flat)
    @test occursin("For \$g_I=0\$, translational invariance is absent and the open-chain BdG construction of \\texttt{OBC.tex} must be used instead", map_flat)
    @test occursin(raw"the code does not define the \texttt{mode\_hk} and \texttt{mode\_nk} observables", map_flat)
    @test occursin(raw"The implementation enforces exactly this domain through \texttt{require\_ising\_fourier\_observables}", note_flat)
    @test occursin(raw"Open chains require the open-boundary BdG diagnostics of \texttt{NotesED/OBC.tex}", note_flat)
    @test occursin(raw"nonintegrable large-\(N\) cooling runs do not have Fourier \texttt{mode\_hk} or \texttt{mode\_nk} observables", note_flat)
    @test occursin("mode-energy reconstruction are defined here only for the integrable transverse-field Ising chain with even `N` and spin `:periodic` or `:antiperiodic` boundary conditions", source_flat)
    @test occursin("ED and Tensor-Network Time Discretizations", map_flat)
    @test occursin("the parameter \\(\\tau\\) is an upper bound on the substep size", map_flat)
    @test occursin("M=\\left\\lceil \\frac{t}{\\tau}\\right\\rceil", map_flat)
    @test occursin("\\delta t=\\frac{t}{M}", map_flat)
    @test occursin("not the first-order split \\((e^{-iH_z\\delta t}e^{-iH_x\\delta t})^M\\)", map_flat)
    @test occursin("interleaved gate decomposition of the same full system-bath Hamiltonian", map_flat)
    @test !occursin("Split-Operator Trotter Method", map_flat)
    @test !occursin(raw"A Trotter step of $\delta t = 0.1$ is typically accurate enough", map_flat)
    @test !occursin(raw"\texttt{campaign\_mode\_detuning\_preserves\_px}", map_flat)
    @test occursin("the automatic endpoint source is `ising_mode_detuning_reference`", plan_flat)
    @test occursin("A single MCWF trajectory and a late-time average are diagnostic quantities only", plan_flat)
    @test occursin("requires independent trajectories, stability under the averaging window, and convergence in the retained-system, evolved system-bath, and TDVP sweep-observer bond dimensions", plan_flat)
    @test occursin("The pure-state MPS trajectory representation is still the preferred large-`N` tensor-network route", plan_flat)
    @test occursin("current `N=64` evidence shows that `D = 40` is only a pilot cap", plan_flat)
    @test occursin("choose `Dmax` from a convergence ladder with retained-system, evolved system-bath, and TDVP sweep-observer diagnostics", plan_flat)
    @test occursin("the evolved system-bath cap in cycle 3, the TDVP sweep-observer cap during cycle 3 sweep 4, and the retained system cap in cycle 4", plan_flat)
    @test occursin("whose retained system state, evolved system-bath state, or, when `--tdvp-sweep-progress` is enabled, TDVP sweep-observer history reaches", plan_flat)
    @test occursin("current large-`N` HDF5 campaign records bond-cap and saturation diagnostics", plan_flat)
    @test occursin("not measured truncation-error histories", plan_flat)
    @test occursin("current timing evidence favors process-level MCWF+TDVP diagnostic scans", plan_flat)
    @test occursin("large-`N` validation driver therefore defaults to `--methods mcwf`", plan_flat)
    @test occursin("Density-matrix/MPO runs remain available through explicit `--methods mpo`", plan_flat)
    @test occursin("No internal scheduler is recommended at this stage", plan_flat)
    @test occursin("output ownership, progress ordering, and deterministic seed assignment local to each independent Julia process", plan_flat)
    @test occursin("rather than adding an internal driver scheduler", plan_flat)
    @test occursin("In multi-job plans where `--progress-csv` is supplied, generated per-job progress CSV filenames keep the requested CSV stem", plan_flat)
    @test occursin("single-job plans keep the requested CSV path unchanged", plan_flat)
    @test occursin("Default HDF5 protocol stems include the canonical evolution-method token, including `trotter`", plan_flat)
    @test occursin("`(N, method, evolution method, R, Dmax, te, trajectory index)` tuple", plan_flat)
    @test occursin("The `--te-values` axis requires an explicit `--delta-min/--delta-max` interval", plan_flat)
    @test occursin("`--trajectory-values 1,2,3` is supported for MCWF jobs", plan_flat)
    @test occursin("the deterministic seed rule remains tied to the stored trajectory index", plan_flat)
    @test occursin("`--evolution-method-values trotter,continuous` together with an explicit `--delta-min/--delta-max` interval", plan_flat)
    @test occursin("a TDVP-versus-Trotter table is not confounded by separately estimated setup gaps", plan_flat)
    @test occursin("the generated TDVP commands retain the TDVP-only observer options and the generated Trotter commands omit them", plan_flat)
    @test occursin("In multi-job plans where `--progress-csv` is supplied, generated per-job progress CSV filenames keep the requested CSV stem", driver_flat)
    @test occursin("Single-job plans keep the requested CSV path unchanged", driver_flat)
    @test occursin("Default HDF5 protocol stems include the canonical evolution-method token, including `trotter`", driver_flat)
    @test occursin("each `(N, method, evolution method, R, Dmax, te, trajectory index)` tuple", driver_flat)
    @test occursin("time-ladder jobs share the same physical detuning protocol", driver_flat)
    @test occursin("Fixed-detuning bath-evolution-time ladder", driver_flat)
    @test occursin("fixed-protocol te ladder", driver_flat)
    @test occursin("The trajectory axis is enabled explicitly with `--trajectory-values`", driver_flat)
    @test occursin("store the requested trajectory index used by the deterministic seed rule", driver_flat)
    @test occursin("--evolution-method-values trotter,continuous", driver_flat)
    @test occursin("Evolution-method labels are parsed case-insensitively and emitted in canonical lowercase form", driver_flat)
    @test occursin("`--tdvp-sweep-progress` or a nonzero `--tdvp-outputlevel`", driver_flat)
    @test occursin("retained only on the generated `continuous` child commands and omitted from the generated `trotter` child commands", driver_flat)
    @test occursin("Trotter and TDVP jobs use the same physical detuning protocol", driver_flat)
    @test occursin("The large-`N` driver can now print paired MCWF/MPS Trotter and MCWF+TDVP commands", evidence_flat)
    @test occursin("Plans with `--te-values` generate one child command per requested evolution time", evidence_flat)
    @test occursin("requires an explicit fixed detuning interval", evidence_flat)
    @test occursin("The summary table includes the stored `te` column", evidence_flat)
    @test occursin("It also includes a `time protocol` column", evidence_flat)
    @test occursin("and an `init` column", evidence_flat)
    @test occursin("stored initial-state protocol (`product`, `ground`, `identity`, or `theta=<value>`)", evidence_flat)
    @test occursin("fixed-time trajectory file and a randomized-time trajectory file with the same mean `te` are likewise kept separate", evidence_flat)
    @test occursin("product-state cooling files, ground-state controls, and explicit theta-state files are not combined", evidence_flat)
    @test occursin("including the initial state, `te`, and whether the cycle times are fixed or randomized, rejects duplicate trajectory labels", evidence_flat)
    @test occursin("initial-state protocol, bath-evolution time `te`, and time protocol are shown next to the bond-dimension diagnostics", summary_flat)
    @test occursin("including the initial state, `te`, and whether cycle times are fixed or randomized", summary_flat)
    @test occursin("only the generated TDVP commands carry the TDVP-only observer options", evidence_flat)
    @test occursin("Dmax=64 Paired Trotter/TDVP Descending Comparison", evidence_flat)
    @test occursin("For this finite prefix and cap, TDVP gives lower energies than the Trotter-gate route at every tested `R`", evidence_flat)
    @test occursin("the evolved system-bath effective bond dimension is only lower bounded by `64` for all `R`", evidence_flat)
    @test occursin("The TDVP branch uses the total bath-evolution time `--te 1.0`", evidence_flat)
    @test occursin("this reference is the stored dataset `N64/mcwf/E0 = -84.7765049115883`", evidence_flat)
    @test occursin("The Trotter-TDVP energy difference also includes the Trotter route's splitting error at `tau = 0.2`", evidence_flat)
    @test occursin("R=10 Trotter Step-Size Ladder at Dmax=64", evidence_flat)
    @test occursin("At the same four completed cycles, reducing `tau` from `0.2` to `0.1` lowers the Trotter energy density", evidence_flat)
    @test occursin("it is not an equal-cycle comparison with the TDVP row", evidence_flat)
    @test occursin("its elapsed time differs because the ladder row is an independent single-`R` job", evidence_flat)
    @test occursin("evidence that both Trotter step size and MCWF sampling cadence affect the finite-prefix comparison", evidence_flat)
    @test occursin("changing `tau` also changes the jump-sampling cadence", evidence_flat)
    @test occursin("not evidence of scalable ground-state cooling", evidence_flat)
    @test occursin("These rows should not be read as current production recommendations", plan_flat)
    @test occursin("Paper-level data should record the stop-on-cap metadata, the TDVP sweep-level bond trace, and enough independent trajectories", plan_flat)
    @test occursin("Late-time or best-prefix energy vs R", plan_flat)
    @test occursin("report this first as a finite-window diagnostic", plan_flat)
    @test occursin("promote it to a steady-state energy only after trajectory and bond-dimension convergence have been demonstrated", plan_flat)
    @test occursin("Late-time or best-prefix energy vs N", plan_flat)
    @test occursin("report the single-Δ versus multi-Δ comparison first as finite-window scaling", plan_flat)
    @test occursin("promote it to steady-state scaling only after trajectory and bond-dimension convergence have been demonstrated", plan_flat)
    @test occursin("Noise-response diagnostics", plan_flat)
    @test occursin("promote this to a robustness claim only after the same trajectory and bond-dimension convergence checks", plan_flat)
    @test occursin("traj cycles/hour | user time", plan_flat)
    @test occursin("serial, one driver process | 1 | 1 | `R=2` then `R=5` | 287.70 s | 50.05", plan_flat)
    @test occursin("serial, one driver process | 1 | 16 | `R=2` then `R=5` | 284.34 s | 50.64", plan_flat)
    @test occursin("two independent processes | 1 | 1 | `R=2` and `R=5` concurrently | 179.28 s | 80.32", plan_flat)
    @test occursin("The throughput column counts four completed trajectory-cycles: two completed cycles for the `R=2` job and two completed cycles for the `R=5` job", plan_flat)
    @test occursin("first verifies `mode_nk = mode_occupation_from_hk(mode_hk)`", evidence_flat)
    @test occursin("paired `NaN` entries accepted only for deliberately unmeasured strided rows", evidence_flat)
    @test occursin("It also verifies `mode_ek_values = mode_energies_Jh(mode_k_indices,J,h,N)`", evidence_flat)
    @test occursin("the stored positive gaps are tied to the same mode grid and Hamiltonian parameters", evidence_flat)
    @test occursin("uses the library routine `ising_energy_from_mode_hk` to reconstruct the integrable-Ising energy on the measured mode rows", evidence_flat)
    @test occursin("The library routine `mode_measurement_cycle_rows` is the shared source of truth for the cycle-list contract", evidence_flat)
    @test occursin("requires the measured cycles to be nonempty, sorted, unique, and in range", evidence_flat)
    @test occursin("The larger validator `validate_mode_measurement_rows` also checks the `mode_nk = mode_occupation_from_hk(mode_hk)` relation", evidence_flat)
    @test occursin("rejects non-finite measured `mode_hk`, `mode_nk`, or energy rows", evidence_flat)
    @test occursin("malformed or non-finite measured rows", evidence_flat)
    @test occursin("This routine is the source of truth for the energy coefficient", evidence_flat)
    @test occursin("the positive quasiparticle gaps `mode_ek_values`", evidence_flat)
    @test occursin("The stored `mode_ek_values` are positive quasiparticle gaps for resonance labels and plots", evidence_flat)
    @test occursin("they are not, by themselves, the signed reconstruction coefficients on grids that contain special modes", evidence_flat)
    @test occursin("The mode-energy plotting path applies the same positive-gap check", evidence_flat)
    @test occursin("the file is rejected rather than repaired by recomputing coefficients from the root metadata", evidence_flat)
    @test occursin("E_{\\mathrm{modes}}(t)=\\frac{\\Lambda}{2} \\sum_{k\\in\\mathrm{grid}(g_F)}\\operatorname{coeff}_k\\,h_k(t)", evidence_flat)
    @test occursin("last measured mode row", evidence_flat)
    @test occursin("mode_gF_source = \"reference\"", evidence_flat)
    @test occursin("includes the canonical evolution-method token (`trotter` or `continuous`), the evolution time `te`, mode-measurement suffixes", evidence_flat)
    @test occursin("Generated per-job progress CSV filenames in a parallel plan reuse the same HDF5 protocol stem", evidence_flat)
    @test occursin("Plans with `--trajectory-values` also add a `_trajk` token", evidence_flat)
    @test occursin("`trajectory_indices` dataset", evidence_flat)
    @test occursin("`summarize_largeN_bond_dimensions.jl --combine-trajectories` groups compatible rows by the physical protocol", evidence_flat)
    @test occursin("rejects duplicate trajectory labels", evidence_flat)
    @test occursin("not a reconstructed cycle-aligned ensemble time series", evidence_flat)
    @test occursin("If some member files do not contain detuning histories", evidence_flat)
    @test occursin("unknownxq/M", evidence_flat)
    @test occursin("not_converged_tdvp_sweep_cap", evidence_flat)
    @test occursin("not_converged_system_and_evolved_and_tdvp_sweep_cap", evidence_flat)
    @test occursin("| 1 | 32 | 5 | 1.44660215 | 2.09208 | >=32 | >=32 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 2 | 2 | 2:7 | 2:7 | 48.7 s | 2:8 | 714.6 s |", evidence_flat)
    @test occursin("the retained system MPS and the evolved system-bath MPS first reach `Dmax = 32` in cycle 2", evidence_flat)
    @test occursin("while the TDVP sweep observer first reaches the cap in cycle 2 sweep 7", evidence_flat)
    @test occursin("validation driver defaults to the MCWF/MPS method for large-system campaigns", evidence_flat)
    @test occursin("MPO density-matrix method remains an explicit small-system validation option", evidence_flat)
    @test occursin("peak tdvp sweep max", evidence_flat)
    @test occursin("tdvp sweep sat", evidence_flat)
    @test occursin("Forty-Cycle MCWF+TDVP Stop-on-Cap Diagnostics", evidence_flat)
    @test occursin("| 5 | 96 | 5 | 0.66394232 | >=96 | >=96 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 4 | 3 | 3:4 | 3:4 | 334.2 s | 5:4 |", evidence_flat)
    @test occursin("legacy first transient cap", evidence_flat)
    @test occursin("Current progress summaries report separate `evolved cap`, `tdvp sweep cap`, and `first transient cap` columns", evidence_flat)
    @test occursin("| 2 | 96 | 3/40 | 0.98249764 | 95 | >=96 | not_converged_evolved_cap | 3:6 | 148.7 s | 1075.2 s |", evidence_flat)
    @test occursin("| 2 | 128 | 3/40 | 0.98236229 | 120 | >=128 | not_converged_evolved_cap | 3:8 | 281.9 s | 1171.6 s |", evidence_flat)
    @test occursin("does not move the first cap event beyond cycle 3", evidence_flat)
    @test occursin("summarized as `n/a`, not as a measured zero-dimensional state", evidence_flat)
    @test occursin("reports `Dtdvp_sweep_eff = n/a` for these legacy files", evidence_flat)
    @test occursin("MCWF+TDVP Stop-on-Cap Scan at te=1.0", evidence_flat)
    @test occursin("| 5 | 96 | 6/40 | 0.95391585 | 0.95391585 | 93 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | 6 | 6 | 678.1 s |", evidence_flat)
    @test occursin("lowering `te` from `2.0` to `1.0` materially delays the first cap event", evidence_flat)
    @test occursin("test `te = 0.5` at `Dmax = 96`", evidence_flat)
    @test occursin("Focused MCWF+TDVP R=2 and R=5 Probes at te=0.5", evidence_flat)
    @test occursin("| 2 | 0.5 | 96 | 11/40 | 1.10014440 | 1.10014440 | 86 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | 11 | 11 | 619.7 s |", evidence_flat)
    @test occursin("| 5 | 0.5 | 96 | 12/40 | 1.03468046 | 1.02937119 | 90 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | 12 | 12 | 744.7 s |", evidence_flat)
    @test occursin("for `R = 2`, the cap moves from cycle 5 at `te = 1.0` to cycle 11 at `te = 0.5`", evidence_flat)
    @test occursin("for `R = 5`, it moves from cycle 6 to cycle 12", evidence_flat)
    @test occursin("argues against the simple rule \"make `te` smaller\"", evidence_flat)
    @test occursin("Random-Schedule MCWF+TDVP Probe at te=1.0", evidence_flat)
    @test occursin("| 2 | random | 1.0 | 96 | 6/40 | 0.99951656 | 0.99951656 | >=96 | >=96 | >=96 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 6 | 6 | 6 | 1051.2 s |", evidence_flat)
    @test occursin("| 5 | random | 1.0 | 96 | 5/40 | 1.12466000 | 1.12466000 | 78 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 341.3 s |", evidence_flat)
    @test occursin("`0.99951656` instead of `1.04543594`", evidence_flat)
    @test occursin("this one-seed diagnostic does not give evidence of a scalable low-entanglement route to the ground state", evidence_flat)
    @test occursin("Randomized-Time MCWF+TDVP Probe at Mean te=1.0", evidence_flat)
    @test occursin("| 2 | 1.0 | 96 | 7/40 | 1.09926433 | 1.09097226 | >=96 | >=96 | >=96 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 7 | 7 | 7 | 1041.6 s |", evidence_flat)
    @test occursin("| 10 | 1.0 | 96 | 8/40 | 1.07882431 | 1.07882431 | 91 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | none | 8 | 8 | 861.9 s |", evidence_flat)
    @test occursin("| 10 | 8 | 2.46945966 | 1.06039527 | 1.07882431 | 91 | 96 | 861.9 s |", evidence_flat)
    @test occursin("The best randomized-time result is `R = 10` with `E/N = 1.07882431`", evidence_flat)
    @test occursin("does not support it as a solution to the large-N bond-growth bottleneck", evidence_flat)
    @test occursin("Post-Krylov-Expansion MCWF+TDVP N=64 Stop-on-Cap Probe", evidence_flat)
    @test occursin("flat pre-expansion TDVP traces as evidence about the corrected implementation", evidence_flat)
    @test occursin("| 32 | 2 | 3/8 | 1.11215604 | 1.08753626 | 24 | >=32 | >=32 | not_converged_evolved_and_tdvp_sweep_cap | none | 3 | 3 | 111.4 s |", evidence_flat)
    @test occursin("| 64 | 2 | 4/8 | 1.10143056 | 1.08753626 | 53 | >=64 | >=64 | not_converged_evolved_and_tdvp_sweep_cap | none | 4 | 4 | 443.2 s |", evidence_flat)
    @test occursin("| 64 | 10 | 4 | 1.34697800 | 1.21672165 | 50 | 64 | 633.1 s |", evidence_flat)
    @test occursin("Corrected TDVP dynamics is no longer flat", evidence_flat)
    @test occursin("still far above `E0/N = -1.3246328892`", evidence_flat)
    @test occursin("at least `64` by the fourth cooling cycle", evidence_flat)
    @test occursin("Dmax=64 Descending R=10 Follow-up", evidence_flat)
    @test occursin("| 10 | 64 | 4/8 | 0.87319302 | 0.87319302 | 56 | >=64 | >=64 | not_converged_evolved_and_tdvp_sweep_cap | none | 4 | 4 | 211.4 s |", evidence_flat)
    @test occursin("| 4 | 2.18883925 | 0.87319302 | 56 | 64 | 211.4 s |", evidence_flat)
    @test occursin("lowers the best observed prefix from the corresponding `Dcap = 32` value `0.95514749` to `0.87319302`", evidence_flat)
    @test occursin("it does not establish scalable ground-state cooling", evidence_flat)
    @test occursin("Dmax=64 Descending All-R Reproducibility Scan", evidence_flat)
    @test occursin("| 1 | 64 | 5/8 | 1.39308425 | 1.37238762 | >=64 | >=64 | >=64 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 5 | 5 | 5 | 459.0 s |", evidence_flat)
    @test occursin("| 10 | 64 | 4/8 | 0.87319302 | 0.87319302 | 56 | >=64 | >=64 | not_converged_evolved_and_tdvp_sweep_cap | none | 4 | 4 | 263.0 s |", evidence_flat)
    @test occursin("At `Dcap = 64`, descending `R = 10` gives the best capped prefix among the tested frequency counts", evidence_flat)
    @test occursin("driver default seed `20260617`", evidence_flat)
    @test occursin("Dmax=128 Descending R=10 Follow-up", evidence_flat)
    @test occursin("| 10 | 128 | 5/12 | 0.84528025 | 0.84528025 | 116 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 803.4 s |", evidence_flat)
    @test occursin("| 5 | 1.90821883 | 0.84528025 | 116 | 128 | 803.4 s |", evidence_flat)
    @test occursin("trajectory seed `[84360618]`", evidence_flat)
    @test occursin("the first three completed-cycle energies match exactly", evidence_flat)
    @test occursin("Dmax=128 Descending Remaining Frequencies", evidence_flat)
    @test occursin("trajectory seeds are `[84270618, 84280618, 84310618]`", evidence_flat)
    @test occursin("this row is therefore a fixed-minimum-detuning reference", evidence_flat)
    @test occursin("| 1 | 128 | 6/12 | 1.38967820 | 1.37238762 | 126 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 6 | 6 | 1741.8 s |", evidence_flat)
    @test occursin("| 2 | 128 | 5/12 | 0.88774576 | 0.88774576 | 116 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 933.0 s |", evidence_flat)
    @test occursin("| 5 | 128 | 5/12 | 1.04315832 | 1.04315832 | 115 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 843.8 s |", evidence_flat)
    @test occursin("| 1 | 6 | 0.50511675 | 1.38967820 | 126 | 128 | 1741.8 s |", evidence_flat)
    @test occursin("At `Dcap = 128`, descending `R = 10` remains the best capped prefix among the tested frequency counts", evidence_flat)
    @test occursin("Dmax=128 Descending R=10 Probe at te=0.5", evidence_flat)
    @test occursin("trajectory seed `[84360618]`", evidence_flat)
    @test occursin("| 10 | 0.5 | 128 | 10/20 | 1.00873665 | 1.00873665 | 113 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | 831.9 s | bond_cap |", evidence_flat)
    @test occursin("| 10 | 0.50511675 | 1.00873665 | 113 | 128 | 831.9 s |", evidence_flat)
    @test occursin("reducing `te` from `1.0` to `0.5` delays the evolved and TDVP-sweep cap from cycle 5 to cycle 10", evidence_flat)
    @test occursin("cap-delay mechanism rather than a route to the ground state", evidence_flat)
    @test occursin("Near-Ground Initial-State Control", evidence_flat)
    @test occursin("`initial E/N`, `initial relE`, and `initial overlap`", evidence_flat)
    @test occursin("make `--init-state ground` controls auditable from the same table", evidence_flat)
    @test occursin("| initial E/N | initial relE | initial overlap | final E/N |", summary_flat)
    @test occursin("| initial E/N | initial overlap | final E/N | best E/N |", summary_flat)
    @test occursin("`--init-state ground`", evidence_flat)
    @test occursin("It reuses the system ground state already computed by `setup_problem`", evidence_flat)
    @test occursin("channel-preservation and bond-growth control", evidence_flat)
    @test occursin("Generated HDF5 filenames include `_initground`", evidence_flat)
    @test occursin("The `ground` initial state reuses the system ground state already computed by", driver_flat)
    @test occursin("This is a near-ground channel benchmark for bond growth and energy drift", driver_flat)
    @test occursin("The driver also supports `--init-state ground`", plan_flat)
    @test occursin("near-ground channel-preservation and bond-growth control", plan_flat)
    @test occursin("First N=64 R=10 Ground-State Control", evidence_flat)
    @test occursin("| 10 | 128 | 8/12 | -1.32463289 | 1.00000 | -1.25614747 | -1.32463289 | 121 | >=128 | >=128 |", evidence_flat)
    @test occursin("The `initial E/N` and `initial overlap` columns verify", evidence_flat)
    @test occursin("delays the `Dmax = 128` evolved/TDVP cap from cycle 5 to cycle 8", evidence_flat)
    @test occursin("fixed descending channel is still not an exact ground-state fixed point", evidence_flat)
    @test occursin("The first `N = 64`, `R = 10`, `Dmax = 128`, `te = 1.0`, descending", plan_flat)
    @test occursin("monotone heating and eventual evolved/TDVP cap saturation", plan_flat)
    @test occursin("Remaining N=64 Ground-State Frequency Controls", evidence_flat)
    @test occursin("| 1 | 128 | 8/12 | -1.32463289 | 1.00000 | -1.21970618 | -1.32463289 | 116 | >=128 | >=128 |", evidence_flat)
    @test occursin("| 2 | 128 | 7/12 | -1.32463289 | 1.00000 | -1.24703609 | -1.32463289 | 108 | >=128 | >=128 |", evidence_flat)
    @test occursin("| 5 | 128 | 8/12 | -1.32463289 | 1.00000 | -1.25381271 | -1.32463289 | 106 | >=128 | >=128 |", evidence_flat)
    @test occursin("final energy ordering `R = 10 < R = 5 < R = 2 < R = 1`", evidence_flat)
    @test occursin("The companion `R = 1,2,5` controls at the same cap", plan_flat)
    @test occursin("none is an exact ground-state fixed point at `Dmax = 128`", plan_flat)
    @test occursin("descending detuning order", note_flat)
    @test occursin("all four frequency counts \\(R=1,2,5,10\\)", note_flat)
    @test occursin("same default seed as the standalone \\(R=10\\) follow-up", note_flat)
    @test occursin("trajectory seed \\(84360618\\)", note_flat)
    @test occursin("first three completed-cycle energies are identical to the stored \\(D_{\\max}=64\\), \\(R=10\\) trajectory prefix", note_flat)
    @test occursin("D_{\\mathrm{sb}}^{\\mathrm{eff}}\\geq 128", note_flat)
    @test occursin("0.87319302", note_flat)
    @test occursin("0.84528025", note_flat)
    @test occursin("The remaining frequencies \\(R=1,2,5\\) were then repeated at the same \\(D_{\\max}=128\\)", note_flat)
    @test occursin("\\(R=1\\) has only one detuning grid point, namely \\(\\delta_{\\min}\\)", note_flat)
    @test occursin("1 & 6/12 & 1.38967820 & 1.37238762 & 126", note_flat)
    @test occursin("2 & 5/12 & 0.88774576 & 0.88774576 & 116", note_flat)
    @test occursin("5 & 5/12 & 1.04315832 & 1.04315832 & 115", note_flat)
    @test occursin("10 & 5/12 & 0.84528025 & 0.84528025 & 116", note_flat)
    @test occursin("Thus \\(R=10\\) remains the best of this fixed descending set at \\(D_{\\max}=128\\)", note_flat)
    @test occursin("with the shorter evolution time \\(t_e=0.5\\)", note_flat)
    @test occursin("1.00873665", note_flat)
    @test occursin("delays the cap from cycle \\(5\\) to cycle \\(10\\)", note_flat)
    @test occursin("a smaller evolution time is a cap-delay mechanism rather than evidence of ground-state cooling", note_flat)
    @test occursin("1.37238762", note_flat)
    @test occursin("calculation is still cap-limited", note_flat)
    @test occursin("--init-state theta --theta 0.0 --measure-modes", evidence_flat)
    @test occursin("mode_gF_source = \"reference\"", evidence_flat)
    @test occursin("mixed-parity state for the periodic Ising chain in the code basis", evidence_flat)
    @test occursin("First Parity-Definite N=64 Mode Scan", evidence_flat)
    @test occursin("| 10 | 10/10 | -1.050000000002 | -1.050000000002 | 0.19542960 | 1 | 1 | 1 | state | 1.208e-12 |", evidence_flat)
    @test occursin("selected grid was half-integer (`mode_gF = -1`), so it contained no special modes", evidence_flat)
    @test occursin("code-unit positive gap stored in HDF5 as `mode_ek_values`", evidence_flat)
    @test occursin("On integer grids with special modes, however, the signed coefficient in the library routine must be used rather than replacing it by the positive gap", evidence_flat)
    @test occursin("gives `E/N = h = -1.05`", evidence_flat)
    @test occursin("it does not show cooling", evidence_flat)
    @test occursin("increasing the number of detunings alone does not produce cooling", evidence_flat)

    @test occursin("n_k^{\\mathrm{Bog}} = \\langle \\hat n_k\\rangle = \\frac{1+\\langle h_k\\rangle}{2}", map_flat)
    @test occursin("This occupation should not be confused with the raw Fourier occupation", map_flat)
    @test occursin("\\operatorname{coeff}_k=w_k", map_flat)
    @test occursin("where \$J\$ is the coupling strength between neighboring spins, \$h_x\$ is the transverse field, \$h_z\$ is the longitudinal field", note_flat)
    @test occursin("limits \$h_z = 0\$ (transverse-field Ising model) and \$h_x = 0\$ (classical diagonal Ising model)", note_flat)
    @test occursin("`H = J sum_i Z_i Z_{i+1} + hx sum_i X_i + hz sum_i Z_i`, where `hx` is the transverse field and `hz` is the longitudinal field", params_flat)

    forbidden = [
        "allows for the preparation of the ground state",
        "the energy of the system is reduced via its interaction",
        "exploiting the low-entanglement structure of the steady states",
        "exploiting the low-entanglement structure of the states involved in the process",
        "algorithm effectively prepares the ground state",
        "confirming the ability of the cooling algorithm to prepare low-energy states",
        "the energy exchange between the system \$s\$ and the bath \$b\$ leads to a decrease of",
        "demonstrating the effectiveness of the cooling algorithm in preparing low-energy states",
        "demonstrating its robustness against depolarizing noise",
        "the algorithm still achieves significant cooling and ground state preparation fidelity",
        "resilient to experimental noise",
        "investigate the robustness of the cooling algorithm in realistic scenarios",
        "the error remains small even for the largest system size",
        "ground state fidelity decreases exponentially",
        "the steady-state energy density",
        "the energy of the steady state is estimated",
        "the bond dimension is truncated to a maximum value of \$d \\leq 100\$",
        "each trajectory starts from the same pure product state, and stochastic pauli errors are sampled after each cooling step. the bond dimension is \$d \\leq 40\$",
        "with a bond dimension of \$d \\leq 100\$",
        "h_z\$ and \$h_x\$ are the transverse and longitudinal magnetic fields",
        "\$h_z = 0\$ (classical) and \$h_x = 0\$ (transverse field ising model)",
        "check whether the ground state is reached",
    ]
    @test all(!occursin(phrase, note_lower) for phrase in forbidden)

    stale_plan_phrases = [
        "time-averaging the steady state",
        "average last ~100 steps",
        "this is already the faster method in the codebase",
        "systematic runs for the paper:",
        "demonstrate and study these strategies",
        "noise robustness",
        "steady-state energy vs r",
        "steady-state energy vs n",
        "bond dimension d ≤ 40 for a pure state",
        "bond dimension d <= 40 for a pure state",
    ]
    @test all(!occursin(phrase, plan_lower) for phrase in stale_plan_phrases)
    @test !occursin("historical truncation diagnostics", note_flat)
    @test !occursin("record truncation and saturation diagnostics", evidence_flat)
end
