using Test

normalize_ws(s::AbstractString) = replace(s, r"\s+" => " ")

@testset "TN note large-N cooling qualifications" begin
    note_path = joinpath(@__DIR__, "..", "Notes", "NotesTN", "CoolingAlgTN.tex")
    map_path = joinpath(@__DIR__, "..", "Notes", "NotesED", "MapToSpin.tex")
    evidence_path = joinpath(@__DIR__, "..", "docs", "largeN_effective_bond_dimensions.md")
    plan_path = joinpath(@__DIR__, "..", "docs", "multi_frequency_cooling_plan.md")

    note_text = read(note_path, String)
    note_flat = normalize_ws(note_text)
    note_lower = lowercase(note_flat)
    map_flat = normalize_ws(read(map_path, String))
    evidence_flat = normalize_ws(read(evidence_path, String))
    plan_flat = normalize_ws(read(plan_path, String))
    plan_lower = lowercase(plan_flat)

    # These anchors intentionally couple the note to the source documents.
    # Update them together when the notation or bond-dimension evidence changes.
    @test occursin("We study a repeated bath-reset cooling map whose intended fixed point", note_flat)
    @test occursin("Whether a given implementation prepares the ground state is a dynamical and numerical question", note_flat)
    @test occursin("This low-entanglement assumption is part of the numerical validation problem", note_flat)
    @test occursin("when the transient system-bath state or the TDVP sweep reaches the imposed bond cap", note_flat)
    @test occursin("not as a final demonstration of ground-state preparation", note_flat)
    @test occursin("Two cooling cycles are not physically meaningful", note_flat)
    @test occursin("driver now treats MCWF/MPS as the default production-sized tensor-network path", note_flat)
    @test occursin("they do not establish scalable cooling to the ground state", note_flat)
    @test occursin("historical truncation diagnostics", note_flat)
    @test occursin("finite-window noise-response diagnostics", note_flat)
    @test occursin("historical noisy MPO panels as finite-window diagnostics of the truncated channel response to the applied noise model", note_flat)
    @test occursin("a robustness claim requires the same bond-dimension, positivity, and trajectory-convergence checks", note_flat)
    @test occursin("archived pilot outputs use truncation caps up to \\(D\\leq 100\\)", note_flat)
    @test occursin("individual plotted panels below state their own fixed bond caps", note_flat)
    @test occursin("The displayed fixed-bond MPO panels use system sizes \\(N=50,100\\), bond dimension \\(D\\leq 20\\)", note_flat)
    @test occursin("archived pilot outputs use trajectory caps up to \\(D\\leq 40\\)", note_flat)
    @test occursin("individual plotted panels below state their own fixed trajectory bond caps", note_flat)
    @test occursin("Each trajectory starts from the same pure product state, and stochastic Pauli errors are sampled after each cooling step. The bond dimension is \$D \\leq 20\$", note_flat)
    @test occursin("D_{\\mathrm{sb}}^{\\mathrm{eff}}=394, 862, 518, 737", note_flat)
    @test occursin("R = 1: Dsys_eff = 309, Dsb_eff = 394", evidence_flat)
    @test occursin("R = 2: Dsys_eff = 637, Dsb_eff = 862", evidence_flat)
    @test occursin("R = 5: Dsys_eff = 399, Dsb_eff = 518", evidence_flat)
    @test occursin("R = 10: Dsys_eff = 489, Dsb_eff = 737", evidence_flat)
    @test occursin("Dtdvp_sweep_eff", evidence_flat)
    @test occursin("tdvp_sweep_max_bond", evidence_flat)
    @test occursin("tdvp_sweep_saturation_cycle", evidence_flat)
    @test occursin("`completed/requested periods` column divides those cycle counts by `R`", evidence_flat)
    @test occursin("an `R = 10` row with five completed cycles is shown as only `0.50` completed schedule periods", evidence_flat)
    @test occursin("`visited detunings` column counts distinct stored detuning values", evidence_flat)
    @test occursin("the realized detuning coverage before the cap, not the intended full grid", evidence_flat)
    @test occursin("`traj cycles/hour` is computed as", evidence_flat)
    @test occursin("It is therefore a throughput diagnostic, not a cooling-performance metric", evidence_flat)
    @test occursin("single-run throughput from the stored HDF5 provenance", plan_flat)
    @test occursin("test and study whether these strategies carry over", plan_flat)
    @test occursin("A single MCWF trajectory and a late-time average are diagnostic quantities only", plan_flat)
    @test occursin("requires independent trajectories, stability under the averaging window, and convergence in the retained and transient bond dimensions", plan_flat)
    @test occursin("current timing evidence favors process-level MCWF+TDVP diagnostic scans", plan_flat)
    @test occursin("large-`N` validation driver therefore defaults to `--methods mcwf`", plan_flat)
    @test occursin("Density-matrix/MPO runs remain available through explicit `--methods mpo`", plan_flat)
    @test occursin("No internal scheduler is recommended at this stage", plan_flat)
    @test occursin("output ownership, progress ordering, and deterministic seed assignment local to each independent Julia process", plan_flat)
    @test occursin("rather than adding an internal driver scheduler", plan_flat)
    @test occursin("These rows should not be read as current production recommendations", plan_flat)
    @test occursin("Paper-level data should record the stop-on-cap metadata, the TDVP sweep-level bond trace, and enough independent trajectories", plan_flat)
    @test occursin("Late-time or best-prefix energy vs R", plan_flat)
    @test occursin("report this first as a finite-window diagnostic", plan_flat)
    @test occursin("promote it to a steady-state energy only after trajectory and bond-dimension convergence have been demonstrated", plan_flat)
    @test occursin("Late-time or best-prefix energy vs N", plan_flat)
    @test occursin("report the single-Δ versus multi-Δ comparison first as finite-window scaling", plan_flat)
    @test occursin("promote it to steady-state scaling only after trajectory and bond-dimension convergence have been demonstrated", plan_flat)
    @test occursin("Noise-response diagnostics", plan_flat)
    @test occursin("promote this to a robustness claim only after the same trajectory and bond-dimension convergence checks", plan_flat)
    @test occursin("traj cycles/hour | user time", plan_flat)
    @test occursin("serial, one driver process | 1 | 1 | `R=2` then `R=5` | 287.70 s | 50.05", plan_flat)
    @test occursin("serial, one driver process | 1 | 16 | `R=2` then `R=5` | 284.34 s | 50.64", plan_flat)
    @test occursin("two independent processes | 1 | 1 | `R=2` and `R=5` concurrently | 179.28 s | 80.32", plan_flat)
    @test occursin("The throughput column counts four completed trajectory-cycles: two completed cycles for the `R=2` job and two completed cycles for the `R=5` job", plan_flat)
    @test occursin("uses the library routine `ising_energy_from_mode_hk` to reconstruct the integrable-Ising energy on the measured mode rows", evidence_flat)
    @test occursin("This routine is the source of truth for the energy coefficient", evidence_flat)
    @test occursin("The stored `mode_ek_values` are positive quasiparticle gaps for resonance labels and plots", evidence_flat)
    @test occursin("they are not, by themselves, the signed reconstruction coefficients on grids that contain special modes", evidence_flat)
    @test occursin("E_{\\mathrm{modes}}(t)=\\frac{\\Lambda}{2} \\sum_{k\\in\\mathrm{grid}(g_F)}\\operatorname{coeff}_k\\,h_k(t)", evidence_flat)
    @test occursin("last measured mode row", evidence_flat)
    @test occursin("mode_gF_source = \"reference\"", evidence_flat)
    @test occursin("includes the evolution time `te` and suffixes for non-default detuning schedules and randomized evolution times", evidence_flat)
    @test occursin("not_converged_tdvp_sweep_cap", evidence_flat)
    @test occursin("not_converged_system_and_evolved_and_tdvp_sweep_cap", evidence_flat)
    @test occursin("validation driver defaults to the MCWF/MPS method for large-system campaigns", evidence_flat)
    @test occursin("MPO density-matrix method remains an explicit small-system validation option", evidence_flat)
    @test occursin("peak tdvp sweep max", evidence_flat)
    @test occursin("tdvp sweep sat", evidence_flat)
    @test occursin("Forty-Cycle MCWF+TDVP Stop-on-Cap Diagnostics", evidence_flat)
    @test occursin("| 2 | 96 | 3/40 | 0.98249764 | 95 | >=96 | not_converged_evolved_cap | 3:6 | 148.7 s | 1075.2 s |", evidence_flat)
    @test occursin("| 2 | 128 | 3/40 | 0.98236229 | 120 | >=128 | not_converged_evolved_cap | 3:8 | 281.9 s | 1171.6 s |", evidence_flat)
    @test occursin("does not move the first cap event beyond cycle 3", evidence_flat)
    @test occursin("summarized as `n/a`, not as a measured zero-dimensional state", evidence_flat)
    @test occursin("reports `Dtdvp_sweep_eff = n/a` for these legacy files", evidence_flat)
    @test occursin("MCWF+TDVP Stop-on-Cap Scan at te=1.0", evidence_flat)
    @test occursin("| 5 | 96 | 6/40 | 0.95391585 | 0.95391585 | 93 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | 6 | 6 | 678.1 s |", evidence_flat)
    @test occursin("lowering `te` from `2.0` to `1.0` materially delays the first cap event", evidence_flat)
    @test occursin("test `te = 0.5` at `Dmax = 96`", evidence_flat)
    @test occursin("Focused MCWF+TDVP R=2 and R=5 Probes at te=0.5", evidence_flat)
    @test occursin("| 2 | 0.5 | 96 | 11/40 | 1.10014440 | 1.10014440 | 86 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | 11 | 11 | 619.7 s |", evidence_flat)
    @test occursin("| 5 | 0.5 | 96 | 12/40 | 1.03468046 | 1.02937119 | 90 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | 12 | 12 | 744.7 s |", evidence_flat)
    @test occursin("for `R = 2`, the cap moves from cycle 5 at `te = 1.0` to cycle 11 at `te = 0.5`", evidence_flat)
    @test occursin("for `R = 5`, it moves from cycle 6 to cycle 12", evidence_flat)
    @test occursin("argues against the simple rule \"make `te` smaller\"", evidence_flat)
    @test occursin("Random-Schedule MCWF+TDVP Probe at te=1.0", evidence_flat)
    @test occursin("| 2 | random | 1.0 | 96 | 6/40 | 0.99951656 | 0.99951656 | >=96 | >=96 | >=96 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 6 | 6 | 6 | 1051.2 s |", evidence_flat)
    @test occursin("| 5 | random | 1.0 | 96 | 5/40 | 1.12466000 | 1.12466000 | 78 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 341.3 s |", evidence_flat)
    @test occursin("`0.99951656` instead of `1.04543594`", evidence_flat)
    @test occursin("this one-seed diagnostic does not give evidence of a scalable low-entanglement route to the ground state", evidence_flat)
    @test occursin("Randomized-Time MCWF+TDVP Probe at Mean te=1.0", evidence_flat)
    @test occursin("| 2 | 1.0 | 96 | 7/40 | 1.09926433 | 1.09097226 | >=96 | >=96 | >=96 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 7 | 7 | 7 | 1041.6 s |", evidence_flat)
    @test occursin("| 10 | 1.0 | 96 | 8/40 | 1.07882431 | 1.07882431 | 91 | >=96 | >=96 | not_converged_evolved_and_tdvp_sweep_cap | none | 8 | 8 | 861.9 s |", evidence_flat)
    @test occursin("| 10 | 8 | 2.46945966 | 1.06039527 | 1.07882431 | 91 | 96 | 861.9 s |", evidence_flat)
    @test occursin("The best randomized-time result is `R = 10` with `E/N = 1.07882431`", evidence_flat)
    @test occursin("does not support it as a solution to the large-N bond-growth bottleneck", evidence_flat)
    @test occursin("Post-Krylov-Expansion MCWF+TDVP N=64 Stop-on-Cap Probe", evidence_flat)
    @test occursin("flat pre-expansion TDVP traces as evidence about the corrected implementation", evidence_flat)
    @test occursin("| 32 | 2 | 3/8 | 1.11215604 | 1.08753626 | 24 | >=32 | >=32 | not_converged_evolved_and_tdvp_sweep_cap | none | 3 | 3 | 111.4 s |", evidence_flat)
    @test occursin("| 64 | 2 | 4/8 | 1.10143056 | 1.08753626 | 53 | >=64 | >=64 | not_converged_evolved_and_tdvp_sweep_cap | none | 4 | 4 | 443.2 s |", evidence_flat)
    @test occursin("| 64 | 10 | 4 | 1.34697800 | 1.21672165 | 50 | 64 | 633.1 s |", evidence_flat)
    @test occursin("Corrected TDVP dynamics is no longer flat", evidence_flat)
    @test occursin("still far above `E0/N = -1.3246328892`", evidence_flat)
    @test occursin("at least `64` by the fourth cooling cycle", evidence_flat)
    @test occursin("Dmax=64 Descending R=10 Follow-up", evidence_flat)
    @test occursin("| 10 | 64 | 4/8 | 0.87319302 | 0.87319302 | 56 | >=64 | >=64 | not_converged_evolved_and_tdvp_sweep_cap | none | 4 | 4 | 211.4 s |", evidence_flat)
    @test occursin("| 4 | 2.18883925 | 0.87319302 | 56 | 64 | 211.4 s |", evidence_flat)
    @test occursin("lowers the best observed prefix from the corresponding `Dcap = 32` value `0.95514749` to `0.87319302`", evidence_flat)
    @test occursin("it does not establish scalable ground-state cooling", evidence_flat)
    @test occursin("Dmax=64 Descending All-R Reproducibility Scan", evidence_flat)
    @test occursin("| 1 | 64 | 5/8 | 1.39308425 | 1.37238762 | >=64 | >=64 | >=64 | not_converged_system_and_evolved_and_tdvp_sweep_cap | 5 | 5 | 5 | 459.0 s |", evidence_flat)
    @test occursin("| 10 | 64 | 4/8 | 0.87319302 | 0.87319302 | 56 | >=64 | >=64 | not_converged_evolved_and_tdvp_sweep_cap | none | 4 | 4 | 263.0 s |", evidence_flat)
    @test occursin("At `Dcap = 64`, descending `R = 10` gives the best capped prefix among the tested frequency counts", evidence_flat)
    @test occursin("driver default seed `20260617`", evidence_flat)
    @test occursin("Dmax=128 Descending R=10 Follow-up", evidence_flat)
    @test occursin("| 10 | 128 | 5/12 | 0.84528025 | 0.84528025 | 116 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 803.4 s |", evidence_flat)
    @test occursin("| 5 | 1.90821883 | 0.84528025 | 116 | 128 | 803.4 s |", evidence_flat)
    @test occursin("trajectory seed `[84360618]`", evidence_flat)
    @test occursin("the first three completed-cycle energies match exactly", evidence_flat)
    @test occursin("Dmax=128 Descending Remaining Frequencies", evidence_flat)
    @test occursin("trajectory seeds are `[84270618, 84280618, 84310618]`", evidence_flat)
    @test occursin("this row is therefore a fixed-minimum-detuning reference", evidence_flat)
    @test occursin("| 1 | 128 | 6/12 | 1.38967820 | 1.37238762 | 126 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 6 | 6 | 1741.8 s |", evidence_flat)
    @test occursin("| 2 | 128 | 5/12 | 0.88774576 | 0.88774576 | 116 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 933.0 s |", evidence_flat)
    @test occursin("| 5 | 128 | 5/12 | 1.04315832 | 1.04315832 | 115 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | none | 5 | 5 | 843.8 s |", evidence_flat)
    @test occursin("| 1 | 6 | 0.50511675 | 1.38967820 | 126 | 128 | 1741.8 s |", evidence_flat)
    @test occursin("At `Dcap = 128`, descending `R = 10` remains the best capped prefix among the tested frequency counts", evidence_flat)
    @test occursin("Dmax=128 Descending R=10 Probe at te=0.5", evidence_flat)
    @test occursin("trajectory seed `[84360618]`", evidence_flat)
    @test occursin("| 10 | 0.5 | 128 | 10/20 | 1.00873665 | 1.00873665 | 113 | >=128 | >=128 | not_converged_evolved_and_tdvp_sweep_cap | 831.9 s | bond_cap |", evidence_flat)
    @test occursin("| 10 | 0.50511675 | 1.00873665 | 113 | 128 | 831.9 s |", evidence_flat)
    @test occursin("reducing `te` from `1.0` to `0.5` delays the evolved and TDVP-sweep cap from cycle 5 to cycle 10", evidence_flat)
    @test occursin("cap-delay mechanism rather than a route to the ground state", evidence_flat)
    @test occursin("descending detuning order", note_flat)
    @test occursin("all four frequency counts \\(R=1,2,5,10\\)", note_flat)
    @test occursin("same default seed as the standalone \\(R=10\\) follow-up", note_flat)
    @test occursin("trajectory seed \\(84360618\\)", note_flat)
    @test occursin("first three completed-cycle energies are identical to the stored \\(D_{\\max}=64\\), \\(R=10\\) trajectory prefix", note_flat)
    @test occursin("D_{\\mathrm{sb}}^{\\mathrm{eff}}\\geq 128", note_flat)
    @test occursin("0.87319302", note_flat)
    @test occursin("0.84528025", note_flat)
    @test occursin("The remaining frequencies \\(R=1,2,5\\) were then repeated at the same \\(D_{\\max}=128\\)", note_flat)
    @test occursin("\\(R=1\\) has only one detuning grid point, namely \\(\\delta_{\\min}\\)", note_flat)
    @test occursin("1 & 6/12 & 1.38967820 & 1.37238762 & 126", note_flat)
    @test occursin("2 & 5/12 & 0.88774576 & 0.88774576 & 116", note_flat)
    @test occursin("5 & 5/12 & 1.04315832 & 1.04315832 & 115", note_flat)
    @test occursin("10 & 5/12 & 0.84528025 & 0.84528025 & 116", note_flat)
    @test occursin("Thus \\(R=10\\) remains the best of this fixed descending set at \\(D_{\\max}=128\\)", note_flat)
    @test occursin("with the shorter evolution time \\(t_e=0.5\\)", note_flat)
    @test occursin("1.00873665", note_flat)
    @test occursin("delays the cap from cycle \\(5\\) to cycle \\(10\\)", note_flat)
    @test occursin("a smaller evolution time is a cap-delay mechanism rather than evidence of ground-state cooling", note_flat)
    @test occursin("1.37238762", note_flat)
    @test occursin("calculation is still cap-limited", note_flat)
    @test occursin("--init-state theta --theta 0.0 --measure-modes", evidence_flat)
    @test occursin("mode_gF_source = \"reference\"", evidence_flat)
    @test occursin("mixed-parity state for the periodic Ising chain in the code basis", evidence_flat)
    @test occursin("First Parity-Definite N=64 Mode Scan", evidence_flat)
    @test occursin("| 10 | 10/10 | -1.050000000002 | -1.050000000002 | 0.19542960 | 1 | 1 | 1 | state | 1.208e-12 |", evidence_flat)
    @test occursin("selected grid was half-integer (`mode_gF = -1`), so it contained no special modes", evidence_flat)
    @test occursin("code-unit positive gap stored in HDF5 as `mode_ek_values`", evidence_flat)
    @test occursin("On integer grids with special modes, however, the signed coefficient in the library routine must be used rather than replacing it by the positive gap", evidence_flat)
    @test occursin("gives `E/N = h = -1.05`", evidence_flat)
    @test occursin("it does not show cooling", evidence_flat)
    @test occursin("increasing the number of detunings alone does not produce cooling", evidence_flat)

    @test occursin("n_k^{\\mathrm{Bog}} = \\langle \\hat n_k\\rangle = \\frac{1+\\langle h_k\\rangle}{2}", map_flat)
    @test occursin("This occupation should not be confused with the raw Fourier occupation", map_flat)
    @test occursin("\\operatorname{coeff}_k=w_k", map_flat)

    forbidden = [
        "allows for the preparation of the ground state",
        "the energy of the system is reduced via its interaction",
        "exploiting the low-entanglement structure of the steady states",
        "exploiting the low-entanglement structure of the states involved in the process",
        "algorithm effectively prepares the ground state",
        "confirming the ability of the cooling algorithm to prepare low-energy states",
        "demonstrating the effectiveness of the cooling algorithm in preparing low-energy states",
        "demonstrating its robustness against depolarizing noise",
        "the algorithm still achieves significant cooling and ground state preparation fidelity",
        "resilient to experimental noise",
        "investigate the robustness of the cooling algorithm in realistic scenarios",
        "the error remains small even for the largest system size",
        "ground state fidelity decreases exponentially",
        "the steady-state energy density",
        "the energy of the steady state is estimated",
        "the bond dimension is truncated to a maximum value of \$d \\leq 100\$",
        "each trajectory starts from the same pure product state, and stochastic pauli errors are sampled after each cooling step. the bond dimension is \$d \\leq 40\$",
        "with a bond dimension of \$d \\leq 100\$",
    ]
    @test all(!occursin(phrase, note_lower) for phrase in forbidden)

    stale_plan_phrases = [
        "time-averaging the steady state",
        "average last ~100 steps",
        "this is already the faster method in the codebase",
        "systematic runs for the paper:",
        "demonstrate and study these strategies",
        "noise robustness",
        "steady-state energy vs r",
        "steady-state energy vs n",
    ]
    @test all(!occursin(phrase, plan_lower) for phrase in stale_plan_phrases)
end
